name: Create File Workflow
# ok

on:
  push:
    branches:
      - main

jobs:
  createFile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: DeepKumbhare85/testdata

      - run: pwd
      - run: echo $GITHUB_WORKSPACE
      - run: echo ${{ github.repository }}
      - run: touch ./db-example.json
      - run: touch db-example2.json
      - run: touch $GITHUB_WORKSPACE/db-example3.json
      - run: ls -la
